// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBypmGC2EvT0rP86d4dBzO1eveoNoKNMMA',
    appId: '1:684473673095:web:2889a5030634c875c21f22',
    messagingSenderId: '684473673095',
    projectId: 'signin-df45a',
    authDomain: 'signin-df45a.firebaseapp.com',
    storageBucket: 'signin-df45a.firebasestorage.app',
    measurementId: 'G-RJQHVZNTHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQiSr0fo7k36HldoaJ2J97Km0t3UBe3k',
    appId: '1:684473673095:android:ae70c90c582790fbc21f22',
    messagingSenderId: '684473673095',
    projectId: 'signin-df45a',
    storageBucket: 'signin-df45a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5WPUUf7MQ5cQwN6aRANqNpqp-yJwa3Bk',
    appId: '1:684473673095:ios:f2ff1d5d3dce70f2c21f22',
    messagingSenderId: '684473673095',
    projectId: 'signin-df45a',
    storageBucket: 'signin-df45a.firebasestorage.app',
    iosBundleId: 'com.example.tired',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5WPUUf7MQ5cQwN6aRANqNpqp-yJwa3Bk',
    appId: '1:684473673095:ios:f2ff1d5d3dce70f2c21f22',
    messagingSenderId: '684473673095',
    projectId: 'signin-df45a',
    storageBucket: 'signin-df45a.firebasestorage.app',
    iosBundleId: 'com.example.tired',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBypmGC2EvT0rP86d4dBzO1eveoNoKNMMA',
    appId: '1:684473673095:web:c5a767d3df57aedbc21f22',
    messagingSenderId: '684473673095',
    projectId: 'signin-df45a',
    authDomain: 'signin-df45a.firebaseapp.com',
    storageBucket: 'signin-df45a.firebasestorage.app',
    measurementId: 'G-SGXNBKXSHJ',
  );
}
